# Path to the dataset folder: data/fb15k-237/ and out/fb15k-237/
DATASET: FB15k-237
# The number of worker threads which compute the scores of the constructed rules, should be one less then the number of available cores.
WORKER_THREADS: 30
THRESHOLD_CORRECT_PREDICTIONS: 30

# If set to true, remove the INVERSE_ prefix from relation names in rule output
REMOVE_INVERSE_PREFIX_IN_OUTPUT: true